---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/familias
  label: Familias
  create: all
  match: "**/*"
- type: directory
  path: content/industrias
  label: Industrias
  create: all
  match: "**/*"
  templates:
  - quimica
- type: directory
  path: content/marcas
  label: Marcas
  create: all
  match: "**/*"
- type: directory
  path: content/novatec-construccion
  label: Novatec construccion
  create: all
  match: "**/*"
- type: directory
  path: content/ncmarcas
  label: Ncmarcas
  create: all
  match: "**/*"
- type: directory
  path: content/noticias
  label: Noticias
  create: all
  match: "**/*"
- type: directory
  path: content/servicio-tecnico
  label: Servicio tecnico
  create: all
  match: "**/*"
- type: directory
  path: content/productos
  label: Productos
  create: all
  match: "**/*"
- type: document
  path: content/about
  label: Acerca de nosotros
- type: document
  path: data/social.yml
  label: Social Networks
upload_dir: ''
public_path: https://res.cloudinary.com/novatec
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.26
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.26'
